// Demo-/mockdata die getoond wordt zolang er nog geen echte data is.
// Puur voor visuele weergave — wordt nergens opgeslagen.

export const DEMO_OFFERTES = [
  {
    id: -1,
    nummer: "OFF-2026-0007",
    klant: "Wouters Dakwerken",
    bedrag: 8288.5,
    datum: "2026-07-05",
    geldig_tot: "2026-08-05",
    status_new: "verzonden",
    email: "koen@woutersdakwerken.be",
    phone: "0489 96 00 01",
  },
  {
    id: -2,
    nummer: "OFF-2026-0006",
    klant: "Yannova BV",
    bedrag: 4235.0,
    datum: "2026-07-02",
    geldig_tot: "2026-08-01",
    status_new: "geaccepteerd",
    email: "info@yannova.be",
    phone: "0498 55 22 33",
  },
  {
    id: -3,
    nummer: "OFF-2026-0005",
    klant: "Bouwgroep De Ridder",
    bedrag: 12750.0,
    datum: "2026-06-28",
    geldig_tot: "2026-07-28",
    status_new: "bekeken",
    email: "info@deridder.be",
    phone: "0475 11 22 33",
  },
  {
    id: -4,
    nummer: "OFF-2026-0004",
    klant: "Keukens Peeters",
    bedrag: 3120.75,
    datum: "2026-06-21",
    geldig_tot: "2026-07-21",
    status_new: "concept",
    email: "info@keukenspeeters.be",
    phone: "0491 44 55 66",
  },
  {
    id: -5,
    nummer: "OFF-2026-0003",
    klant: "Interieur Claes",
    bedrag: 6540.0,
    datum: "2026-06-14",
    geldig_tot: "2026-07-14",
    status_new: "afgewezen",
    email: "sofie.claes@gmail.com",
    phone: "0470 12 34 56",
  },
];

export const DEMO_FACTUREN = [
  {
    id: -1,
    nummer: "FAC-2026-0009",
    klant: "Yannova BV",
    totaal_bedrag: 4235.0,
    datum: "2026-07-03",
    vervaldatum: "2026-07-17",
    status: "verzonden",
    document_type: "factuur",
    paid_at: null as string | null,
    email: "info@yannova.be",
    phone: "0498 55 22 33",
  },
  {
    id: -2,
    nummer: "FAC-2026-0008",
    klant: "Wouters Dakwerken",
    totaal_bedrag: 8288.5,
    datum: "2026-06-30",
    vervaldatum: "2026-07-14",
    status: "betaald",
    document_type: "factuur",
    paid_at: "2026-07-06",
    email: "koen@woutersdakwerken.be",
    phone: "0489 96 00 01",
  },
  {
    id: -3,
    nummer: "PRO-2026-0002",
    klant: "Bouwgroep De Ridder",
    totaal_bedrag: 12750.0,
    datum: "2026-06-27",
    vervaldatum: null,
    status: "concept",
    document_type: "proforma",
    paid_at: null,
    email: "info@deridder.be",
    phone: "0475 11 22 33",
  },
  {
    id: -4,
    nummer: "FAC-2026-0007",
    klant: "Keukens Peeters",
    totaal_bedrag: 3120.75,
    datum: "2026-06-12",
    vervaldatum: "2026-06-26",
    status: "vervallen",
    document_type: "factuur",
    paid_at: null,
    email: "info@keukenspeeters.be",
    phone: "0491 44 55 66",
  },
];

export const DEMO_CONTACTS = [
  {
    id: "demo-1",
    type: "bedrijf" as const,
    voornaam: "Koen",
    achternaam: "Wouters",
    email: "koen@woutersdakwerken.be",
    telefoon: "0489 96 00 01",
    bedrijfsnaam: "Wouters Dakwerken",
    bedrijfsgrootte: "6–20",
    bron: "Aanbeveling",
    bericht: "Interesse in offerte voor volledige dakrenovatie.",
    createdAt: "2026-07-05T09:20:00.000Z",
  },
  {
    id: "demo-2",
    type: "particulier" as const,
    voornaam: "Sofie",
    achternaam: "Claes",
    email: "sofie.claes@gmail.com",
    telefoon: "0470 12 34 56",
    bedrijfsnaam: "",
    bedrijfsgrootte: "",
    bron: "Google",
    bericht: "Vraag over plaatsing van nieuwe ramen.",
    createdAt: "2026-07-04T14:05:00.000Z",
  },
  {
    id: "demo-3",
    type: "bedrijf" as const,
    voornaam: "Rachid",
    achternaam: "Talbi",
    email: "info@yannova.be",
    telefoon: "0498 55 22 33",
    bedrijfsnaam: "Yannova BV",
    bedrijfsgrootte: "21–50",
    bron: "Beurs",
    bericht: "Samenwerking voor meerdere projecten bespreken.",
    createdAt: "2026-07-03T11:40:00.000Z",
  },
];

export const DEMO_LEADS = [
  {
    id: -1,
    titel: "Renovatie Vandenberghe",
    stadium: "Lead",
    waarde: 18500,
    kans: 35,
    deadline: "2026-07-05",
    contactpersoon: "Marc Vandenberghe",
    telefoon: "0475 12 34 56",
    email: "marc.vandenberghe@example.be",
    notitie: "Wil eerst een prijsindicatie voor het dakwerk.",
  },
  {
    id: -2,
    titel: "Gevelisolatie Immo Coninckx",
    stadium: "Gekwalificeerd",
    waarde: 42000,
    kans: 55,
    deadline: "2026-07-25",
    contactpersoon: "Els Coninckx",
    telefoon: "0468 22 33 44",
    email: "els@immoconinckx.be",
    notitie: null,
  },
  {
    id: -3,
    titel: "Dakwerken Peeters",
    stadium: "Voorstel",
    waarde: 12800,
    kans: 70,
    deadline: "2026-07-11",
    contactpersoon: "Tom Peeters",
    telefoon: "0472 55 66 77",
    email: null,
    notitie: "Wacht op akkoord van de vrouw, opnieuw bellen donderdag.",
  },
  {
    id: -4,
    titel: "Badkamerrenovatie Janssens",
    stadium: "Onderhandeling",
    waarde: 9600,
    kans: 80,
    deadline: "2026-07-15",
    contactpersoon: "Sofie Janssens",
    telefoon: "0479 88 99 00",
    email: "sofie.janssens@example.be",
    notitie: null,
  },
  {
    id: -5,
    titel: "Nieuwbouw De Vlaming",
    stadium: "Gewonnen",
    waarde: 215000,
    kans: 100,
    deadline: null,
    contactpersoon: "Frank De Vlaming",
    telefoon: "0477 10 20 30",
    email: "frank@develaming.be",
    notitie: null,
  },
];

export const DEMO_DASHBOARD = {
  offertesCount: 7,
  klantenCount: 24,
  gefactureerd: 18650,
  openstaand: 7420,
  actionItems: [
    {
      id: -1,
      title: "Offerte OFF-2026-0007 opvolgen",
      detail: "Verzonden naar Wouters Dakwerken — 3 dagen geen reactie",
      kind: "offerte" as const,
    },
    {
      id: -2,
      title: "Factuur FAC-2026-0007 vervallen",
      detail: "Keukens Peeters — betaalherinnering versturen",
      kind: "factuur" as const,
    },
    {
      id: -3,
      title: "Nieuwe lead: Renovatie Vandenberghe",
      detail: "Aanvraag via website — offerte opmaken",
      kind: "opvolging" as const,
    },
    {
      id: -4,
      title: "Proforma PRO-2026-0002 omzetten",
      detail: "Bouwgroep De Ridder wacht op definitieve factuur",
      kind: "factuur" as const,
    },
  ],
  activity: [
    {
      id: -1,
      text: "Factuur FAC-2026-0008 werd betaald door Wouters Dakwerken",
      time: "2 u",
      kind: "factuur" as const,
    },
    {
      id: -2,
      text: "Offerte OFF-2026-0006 geaccepteerd door Yannova BV",
      time: "5 u",
      kind: "offerte" as const,
    },
    {
      id: -3,
      text: "Betaalherinnering verstuurd naar Keukens Peeters",
      time: "1 d",
      kind: "reminder" as const,
    },
    {
      id: -4,
      text: "Nieuwe lead toegevoegd: Renovatie Vandenberghe",
      time: "1 d",
      kind: "lead" as const,
    },
    {
      id: -5,
      text: "Offerte OFF-2026-0007 verzonden naar Wouters Dakwerken",
      time: "2 d",
      kind: "offerte" as const,
    },
  ],
};
