// Demo-/mockdata die getoond wordt in anonieme voorbeeldmodus
// (`/dashboard/voorbeeld`) zolang er nog geen echte tenant-data is.
// Puur voor visuele weergave — wordt nergens opgeslagen.

const dayOffset = (d: number) => {
  const date = new Date();
  date.setHours(12, 0, 0, 0);
  date.setDate(date.getDate() + d);
  return date.toISOString().slice(0, 10);
};

const hourOffset = (h: number) => {
  const date = new Date();
  date.setMinutes(0, 0, 0);
  date.setHours(date.getHours() + h);
  return date.toISOString();
};

export const DEMO_OFFERTES = [
  {
    id: -1,
    nummer: "OFF-2026-0007",
    klant: "Wouters Dakwerken",
    bedrag: 8288.5,
    datum: dayOffset(-5),
    geldig_tot: dayOffset(25),
    status_new: "verzonden",
    email: "koen@woutersdakwerken.be",
    phone: "0489 96 00 01",
  },
  {
    id: -2,
    nummer: "OFF-2026-0006",
    klant: "Yannova BV",
    bedrag: 4235.0,
    datum: dayOffset(-8),
    geldig_tot: dayOffset(22),
    status_new: "geaccepteerd",
    email: "info@yannova.be",
    phone: "0498 55 22 33",
  },
  {
    id: -3,
    nummer: "OFF-2026-0005",
    klant: "Bouwgroep De Ridder",
    bedrag: 12750.0,
    datum: dayOffset(-12),
    geldig_tot: dayOffset(18),
    status_new: "bekeken",
    email: "info@deridder.be",
    phone: "0475 11 22 33",
  },
  {
    id: -4,
    nummer: "OFF-2026-0004",
    klant: "Keukens Peeters",
    bedrag: 3120.75,
    datum: dayOffset(-19),
    geldig_tot: dayOffset(11),
    status_new: "concept",
    email: "info@keukenspeeters.be",
    phone: "0491 44 55 66",
  },
  {
    id: -5,
    nummer: "OFF-2026-0003",
    klant: "Interieur Claes",
    bedrag: 6540.0,
    datum: dayOffset(-26),
    geldig_tot: dayOffset(4),
    status_new: "afgewezen",
    email: "sofie.claes@gmail.com",
    phone: "0470 12 34 56",
  },
];

export const DEMO_FACTUREN = [
  {
    id: -1,
    nummer: "FAC-2026-0009",
    klant: "Yannova BV",
    totaal_bedrag: 4235.0,
    datum: dayOffset(-7),
    vervaldatum: dayOffset(7),
    status: "verzonden",
    document_type: "factuur",
    paid_at: null as string | null,
    email: "info@yannova.be",
    phone: "0498 55 22 33",
  },
  {
    id: -2,
    nummer: "FAC-2026-0008",
    klant: "Wouters Dakwerken",
    totaal_bedrag: 8288.5,
    datum: dayOffset(-10),
    vervaldatum: dayOffset(4),
    status: "betaald",
    document_type: "factuur",
    paid_at: dayOffset(-4),
    email: "koen@woutersdakwerken.be",
    phone: "0489 96 00 01",
  },
  {
    id: -3,
    nummer: "PRO-2026-0002",
    klant: "Bouwgroep De Ridder",
    totaal_bedrag: 12750.0,
    datum: dayOffset(-13),
    vervaldatum: null as string | null,
    status: "concept",
    document_type: "proforma",
    paid_at: null,
    email: "info@deridder.be",
    phone: "0475 11 22 33",
  },
  {
    id: -4,
    nummer: "FAC-2026-0007",
    klant: "Keukens Peeters",
    totaal_bedrag: 3120.75,
    datum: dayOffset(-28),
    vervaldatum: dayOffset(-14),
    status: "vervallen",
    document_type: "factuur",
    paid_at: null,
    email: "info@keukenspeeters.be",
    phone: "0491 44 55 66",
  },
  {
    id: -5,
    nummer: "FAC-2026-0010",
    klant: "Gemeente Sint-Niklaas",
    totaal_bedrag: 15600.0,
    datum: dayOffset(-3),
    vervaldatum: dayOffset(27),
    status: "verzonden",
    document_type: "factuur",
    paid_at: null,
    email: "facturatie@sint-niklaas.be",
    phone: "03 778 30 00",
  },
];

/** Peppol / e-facturen overzicht (voorbeeldmodus). */
export const DEMO_PEPPOL_FACTUREN = [
  {
    id: -1,
    nummer: "FAC-2026-0009",
    klant: "Yannova BV",
    totaal_bedrag: 4235.0,
    datum: dayOffset(-7),
    peppol_status: "verzonden",
    peppol_last_error: null as string | null,
  },
  {
    id: -2,
    nummer: "FAC-2026-0008",
    klant: "Wouters Dakwerken",
    totaal_bedrag: 8288.5,
    datum: dayOffset(-10),
    peppol_status: "verzonden",
    peppol_last_error: null,
  },
  {
    id: -5,
    nummer: "FAC-2026-0010",
    klant: "Gemeente Sint-Niklaas",
    totaal_bedrag: 15600.0,
    datum: dayOffset(-3),
    peppol_status: "verzonden",
    peppol_last_error: null,
  },
  {
    id: -4,
    nummer: "FAC-2026-0007",
    klant: "Keukens Peeters",
    totaal_bedrag: 3120.75,
    datum: dayOffset(-28),
    peppol_status: "fout",
    peppol_last_error: "Ontvanger niet gevonden op Peppol (demo).",
  },
  {
    id: -3,
    nummer: "PRO-2026-0002",
    klant: "Bouwgroep De Ridder",
    totaal_bedrag: 12750.0,
    datum: dayOffset(-13),
    peppol_status: "niet_verzonden",
    peppol_last_error: null,
  },
];

export const DEMO_PEPPOL_INBOX = [
  {
    id: -101,
    bedrijf_id: 0,
    external_inbox_item_id: "demo-inbox-1",
    peppol_file_id: null as string | null,
    document_type: "invoice",
    sender_peppol_id: "0208:0412345678",
    receiver_peppol_id: "0208:0123456789",
    invoice_number: "LEV-2026-441",
    supplier_name: "Bouwmaterialen Van Acker NV",
    total_amount: 1842.5,
    currency: "EUR",
    issue_date: dayOffset(-2),
    status: "nieuw",
    received_at: hourOffset(-18),
  },
  {
    id: -102,
    bedrijf_id: 0,
    external_inbox_item_id: "demo-inbox-2",
    peppol_file_id: null,
    document_type: "creditnote",
    sender_peppol_id: "9925:BE0456789012",
    receiver_peppol_id: "0208:0123456789",
    invoice_number: "CN-8821",
    supplier_name: "Isolatie Pro BV",
    total_amount: -320.0,
    currency: "EUR",
    issue_date: dayOffset(-5),
    status: "nieuw",
    received_at: hourOffset(-72),
  },
];

export const DEMO_MERCURIUS_FACTUREN = [
  {
    id: -5,
    nummer: "FAC-2026-0010",
    klant: "Gemeente Sint-Niklaas",
    totaal_bedrag: 15600.0,
    datum: dayOffset(-3),
    buyer_reference: "PO-SN-2026-8841",
    mercurius_status: "verzonden",
    mercurius_last_error: null as string | null,
  },
];

/** Contacten-module (KlantRecord-vorm). */
export const DEMO_KLANTEN = [
  {
    id: -1,
    contact_type: "company" as const,
    name: "Wouters Dakwerken",
    company_name: "Wouters Dakwerken",
    first_name: "Koen",
    last_name: "Wouters",
    email: "koen@woutersdakwerken.be",
    phone: "0489 96 00 01",
    address: "Dakstraat 12",
    postcode: "9000",
    city: "Gent",
    country: "BE",
    ondernemingsnummer: "0412345678",
    kvk: "0412345678",
    btw: "BE0412345678",
    peppol_participant_id: "0208:0412345678",
    is_overheid: false,
    mercurius_entiteit_id: null as string | null,
    notes: "Voorkeur: offertes met materiaaldetail.",
  },
  {
    id: -2,
    contact_type: "company" as const,
    name: "Yannova BV",
    company_name: "Yannova BV",
    first_name: "Rachid",
    last_name: "Talbi",
    email: "info@yannova.be",
    phone: "0498 55 22 33",
    address: "Industrieweg 45",
    postcode: "2000",
    city: "Antwerpen",
    country: "BE",
    ondernemingsnummer: "0456789012",
    kvk: "0456789012",
    btw: "BE0456789012",
    peppol_participant_id: "9925:BE0456789012",
    is_overheid: false,
    mercurius_entiteit_id: null,
    notes: "Betalingstermijn 14 dagen.",
  },
  {
    id: -3,
    contact_type: "company" as const,
    name: "Bouwgroep De Ridder",
    company_name: "Bouwgroep De Ridder",
    first_name: "Jan",
    last_name: "De Ridder",
    email: "info@deridder.be",
    phone: "0475 11 22 33",
    address: "Werfplein 3",
    postcode: "2800",
    city: "Mechelen",
    country: "BE",
    ondernemingsnummer: "0123456789",
    kvk: "0123456789",
    btw: "BE0123456789",
    peppol_participant_id: "0208:0123456789",
    is_overheid: false,
    mercurius_entiteit_id: null,
    notes: null,
  },
  {
    id: -4,
    contact_type: "individual" as const,
    name: "Sofie Claes",
    company_name: null,
    first_name: "Sofie",
    last_name: "Claes",
    email: "sofie.claes@gmail.com",
    phone: "0470 12 34 56",
    address: "Kerkstraat 8",
    postcode: "3000",
    city: "Leuven",
    country: "BE",
    ondernemingsnummer: null,
    kvk: null,
    btw: null,
    peppol_participant_id: null,
    is_overheid: false,
    mercurius_entiteit_id: null,
    notes: "Particulier — ramen plaatsen.",
  },
  {
    id: -5,
    contact_type: "company" as const,
    name: "Gemeente Sint-Niklaas",
    company_name: "Gemeente Sint-Niklaas",
    first_name: null,
    last_name: null,
    email: "facturatie@sint-niklaas.be",
    phone: "03 778 30 00",
    address: "Grote Markt 1",
    postcode: "9100",
    city: "Sint-Niklaas",
    country: "BE",
    ondernemingsnummer: "0207411619",
    kvk: "0207411619",
    btw: "BE0207411619",
    peppol_participant_id: "0208:0207411619",
    is_overheid: true,
    mercurius_entiteit_id: "0208:0207411619",
    notes: "Mercurius B2G — bestelbon verplicht.",
  },
];

/** Legacy ContactForm-vorm (landing / oude UI). */
export const DEMO_CONTACTS = [
  {
    id: "demo-1",
    type: "bedrijf" as const,
    voornaam: "Koen",
    achternaam: "Wouters",
    email: "koen@woutersdakwerken.be",
    telefoon: "0489 96 00 01",
    bedrijfsnaam: "Wouters Dakwerken",
    bedrijfsgrootte: "6–20",
    bron: "Aanbeveling",
    bericht: "Interesse in offerte voor volledige dakrenovatie.",
    createdAt: hourOffset(-48),
  },
  {
    id: "demo-2",
    type: "particulier" as const,
    voornaam: "Sofie",
    achternaam: "Claes",
    email: "sofie.claes@gmail.com",
    telefoon: "0470 12 34 56",
    bedrijfsnaam: "",
    bedrijfsgrootte: "",
    bron: "Google",
    bericht: "Vraag over plaatsing van nieuwe ramen.",
    createdAt: hourOffset(-72),
  },
  {
    id: "demo-3",
    type: "bedrijf" as const,
    voornaam: "Rachid",
    achternaam: "Talbi",
    email: "info@yannova.be",
    telefoon: "0498 55 22 33",
    bedrijfsnaam: "Yannova BV",
    bedrijfsgrootte: "21–50",
    bron: "Beurs",
    bericht: "Samenwerking voor meerdere projecten bespreken.",
    createdAt: hourOffset(-96),
  },
];

export const DEMO_LEADS = [
  {
    id: -1,
    titel: "Renovatie Vandenberghe",
    stadium: "Lead",
    waarde: 18500,
    kans: 35,
    deadline: dayOffset(3),
    contactpersoon: "Marc Vandenberghe",
    telefoon: "0475 12 34 56",
    email: "marc.vandenberghe@example.be",
    notitie: "Wil eerst een prijsindicatie voor het dakwerk.",
  },
  {
    id: -2,
    titel: "Gevelisolatie Immo Coninckx",
    stadium: "Gekwalificeerd",
    waarde: 42000,
    kans: 55,
    deadline: dayOffset(14),
    contactpersoon: "Els Coninckx",
    telefoon: "0468 22 33 44",
    email: "els@immoconinckx.be",
    notitie: null as string | null,
  },
  {
    id: -3,
    titel: "Dakwerken Peeters",
    stadium: "Voorstel",
    waarde: 12800,
    kans: 70,
    deadline: dayOffset(5),
    contactpersoon: "Tom Peeters",
    telefoon: "0472 55 66 77",
    email: null as string | null,
    notitie: "Wacht op akkoord van de vrouw, opnieuw bellen donderdag.",
  },
  {
    id: -4,
    titel: "Badkamerrenovatie Janssens",
    stadium: "Onderhandeling",
    waarde: 9600,
    kans: 80,
    deadline: dayOffset(8),
    contactpersoon: "Sofie Janssens",
    telefoon: "0479 88 99 00",
    email: "sofie.janssens@example.be",
    notitie: null,
  },
  {
    id: -5,
    titel: "Nieuwbouw De Vlaming",
    stadium: "Gewonnen",
    waarde: 215000,
    kans: 100,
    deadline: null as string | null,
    contactpersoon: "Frank De Vlaming",
    telefoon: "0477 10 20 30",
    email: "frank@develaming.be",
    notitie: null,
  },
];

export const DEMO_PRIJSLIJST = [
  {
    id: -1,
    omschrijving: "Dakpannen plaatsen",
    eenheid: "m²",
    prijs: 48.5,
    btwPercentage: 6,
    categorie: "Dakwerken",
    isActive: true,
  },
  {
    id: -2,
    omschrijving: "Onderdakfolie plaatsen",
    eenheid: "m²",
    prijs: 12.0,
    btwPercentage: 6,
    categorie: "Dakwerken",
    isActive: true,
  },
  {
    id: -3,
    omschrijving: "Gevelisolatie EPS 12 cm",
    eenheid: "m²",
    prijs: 72.0,
    btwPercentage: 6,
    categorie: "Isolatie",
    isActive: true,
  },
  {
    id: -4,
    omschrijving: "Uurloon vakman",
    eenheid: "uur",
    prijs: 55.0,
    btwPercentage: 21,
    categorie: "Arbeid",
    isActive: true,
  },
  {
    id: -5,
    omschrijving: "Uurloon helper",
    eenheid: "uur",
    prijs: 38.0,
    btwPercentage: 21,
    categorie: "Arbeid",
    isActive: true,
  },
  {
    id: -6,
    omschrijving: "Badkamer tegels plaatsen",
    eenheid: "m²",
    prijs: 65.0,
    btwPercentage: 6,
    categorie: "Afwerking",
    isActive: true,
  },
  {
    id: -7,
    omschrijving: "Werfopruiming",
    eenheid: "forfait",
    prijs: 250.0,
    btwPercentage: 21,
    categorie: "Algemeen",
    isActive: true,
  },
  {
    id: -8,
    omschrijving: "Transport / kraan",
    eenheid: "dag",
    prijs: 480.0,
    btwPercentage: 21,
    categorie: "Algemeen",
    isActive: false,
  },
];

export const DEMO_AFSPRAKEN = [
  {
    id: -1,
    titel: "Werfbezoek Sint-Niklaas",
    beschrijving: "Controle oplevering gevelrenovatie",
    locatie: "Stationsstraat 14, 9100 Sint-Niklaas",
    startTijd: hourOffset(26),
    eindTijd: hourOffset(28),
    status: "bevestigd",
    type: "plaatsbezoek",
  },
  {
    id: -2,
    titel: "Intake Immo Coninckx",
    beschrijving: "Bespreking gevelisolatie-project",
    locatie: "Kantoor ArchonPro",
    startTijd: hourOffset(50),
    eindTijd: hourOffset(51),
    status: "gepland",
    type: "intake",
  },
  {
    id: -3,
    titel: "Offerte bespreken — Yannova",
    beschrijving: "OFF-2026-0006 — laatste vragen over planning",
    locatie: "Videocall",
    startTijd: hourOffset(5),
    eindTijd: hourOffset(6),
    status: "gepland",
    type: "opvolging",
  },
  {
    id: -4,
    titel: "Materiaallevering Wouters Dakwerken",
    beschrijving: "Pannen en onderdakfolie",
    locatie: "Dakstraat 12, Gent",
    startTijd: hourOffset(-20),
    eindTijd: hourOffset(-18),
    status: "afgerond",
    type: "levering",
  },
];

/** Klanten voor factuur-/offerteformulieren in demo. */
export const DEMO_FACTUUR_CUSTOMERS = DEMO_KLANTEN.filter(
  (k) => k.contact_type === "company",
).map((k) => ({
  id: k.id,
  name: k.name,
  company_name: k.company_name,
  first_name: k.first_name,
  last_name: k.last_name,
  address: [k.address, k.postcode, k.city].filter(Boolean).join(", "),
  email: k.email,
  phone: k.phone,
  btw: k.btw,
}));

export const DEMO_DASHBOARD = {
  offertesCount: 7,
  klantenCount: DEMO_KLANTEN.length,
  gefactureerd: 18650,
  openstaand: 7420,
  actionItems: [
    {
      id: -1,
      title: "Offerte OFF-2026-0007 opvolgen",
      detail: "Verzonden naar Wouters Dakwerken — 3 dagen geen reactie",
      kind: "offerte" as const,
    },
    {
      id: -2,
      title: "Factuur FAC-2026-0007 vervallen",
      detail: "Keukens Peeters — betaalherinnering versturen",
      kind: "factuur" as const,
    },
    {
      id: -3,
      title: "Nieuwe lead: Renovatie Vandenberghe",
      detail: "Aanvraag via website — offerte opmaken",
      kind: "opvolging" as const,
    },
    {
      id: -4,
      title: "Proforma PRO-2026-0002 omzetten",
      detail: "Bouwgroep De Ridder wacht op definitieve factuur",
      kind: "factuur" as const,
    },
  ],
  activity: [
    {
      id: -1,
      text: "Factuur FAC-2026-0008 werd betaald door Wouters Dakwerken",
      time: "2 u",
      kind: "factuur" as const,
    },
    {
      id: -2,
      text: "Offerte OFF-2026-0006 geaccepteerd door Yannova BV",
      time: "5 u",
      kind: "offerte" as const,
    },
    {
      id: -3,
      text: "Betaalherinnering verstuurd naar Keukens Peeters",
      time: "1 d",
      kind: "reminder" as const,
    },
    {
      id: -4,
      text: "Nieuwe lead toegevoegd: Renovatie Vandenberghe",
      time: "1 d",
      kind: "lead" as const,
    },
    {
      id: -5,
      text: "Offerte OFF-2026-0007 verzonden naar Wouters Dakwerken",
      time: "2 d",
      kind: "offerte" as const,
    },
  ],
};
