-- Platformfacturen uit Stripe. Alleen toegankelijk via de service role na
-- een expliciete platform-admincontrole in de applicatie.
create table if not exists public.platform_billing_invoices (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.bedrijven(id) on delete cascade,
  stripe_invoice_id text not null unique,
  stripe_customer_id text not null,
  stripe_subscription_id text,
  number text,
  status text not null check (status in ('draft', 'open', 'paid', 'uncollectible', 'void')),
  billing_reason text,
  currency text not null check (char_length(currency) = 3),
  amount_due bigint not null default 0 check (amount_due >= 0),
  amount_paid bigint not null default 0 check (amount_paid >= 0),
  customer_email text,
  hosted_invoice_url text,
  invoice_pdf_url text,
  period_start timestamptz,
  period_end timestamptz,
  paid_at timestamptz,
  livemode boolean not null default false,
  last_event_created_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists platform_billing_invoices_company_created_idx
  on public.platform_billing_invoices (company_id, created_at desc);
create index if not exists platform_billing_invoices_company_status_idx
  on public.platform_billing_invoices (company_id, status);

create table if not exists public.platform_billing_delivery_logs (
  id bigint generated by default as identity primary key,
  invoice_id bigint not null references public.platform_billing_invoices(id) on delete cascade,
  company_id bigint not null references public.bedrijven(id) on delete cascade,
  requested_by uuid references auth.users(id) on delete set null,
  recipient_email text,
  provider text not null default 'stripe',
  status text not null check (status in ('requested', 'test', 'sent', 'failed')),
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists platform_billing_delivery_logs_invoice_created_idx
  on public.platform_billing_delivery_logs (invoice_id, created_at desc);
create index if not exists platform_billing_delivery_logs_company_created_idx
  on public.platform_billing_delivery_logs (company_id, created_at desc);
create index if not exists platform_billing_delivery_logs_requested_by_idx
  on public.platform_billing_delivery_logs (requested_by)
  where requested_by is not null;

alter table public.platform_billing_invoices enable row level security;
alter table public.platform_billing_delivery_logs enable row level security;

revoke all on table public.platform_billing_invoices from anon, authenticated;
revoke all on table public.platform_billing_delivery_logs from anon, authenticated;
grant all on table public.platform_billing_invoices to service_role;
grant all on table public.platform_billing_delivery_logs to service_role;
grant usage, select on sequence public.platform_billing_invoices_id_seq to service_role;
grant usage, select on sequence public.platform_billing_delivery_logs_id_seq to service_role;
